// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionTurnosMedicos.Server.Migrations
{
    [DbContext(typeof(TurnosContext))]
    partial class TurnosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("especialidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("medico");
                });

            modelBuilder.Entity("Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cedula");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("paciente");
                });

            modelBuilder.Entity("SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConflictPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConflictsResolved")
                        .HasColumnType("integer");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsUpdated")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado")
                        .HasAnnotation("Relational:JsonPropertyName", "estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasAnnotation("Relational:JsonPropertyName", "fecha");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("interval")
                        .HasColumnName("hora")
                        .HasAnnotation("Relational:JsonPropertyName", "hora");

                    b.Property<int>("MedicoId")
                        .HasColumnType("integer")
                        .HasColumnName("medico_id")
                        .HasAnnotation("Relational:JsonPropertyName", "medicoId");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id")
                        .HasAnnotation("Relational:JsonPropertyName", "pacienteId");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion")
                        .HasAnnotation("Relational:JsonPropertyName", "ultimaActualizacion");

                    b.HasKey("Id");

                    b.ToTable("turno");
                });
#pragma warning restore 612, 618
        }
    }
}
